name: 'Setup Environment'
description: 'asdfを使用してNode.jsとpnpmをセットアップします'

runs:
  using: 'composite'
  steps:
    - name: Setup asdf
      uses: asdf-vm/actions/setup@v3

    - name: Install asdf plugins
      shell: bash
      run: |
        asdf plugin add nodejs || true
        asdf plugin add pnpm || true

    - name: Install asdf tools
      shell: bash
      run: asdf install

    - name: Verify pnpm installation
      shell: bash
      run: |
        echo "PATH: $PATH"
        asdf current
        which pnpm || echo "pnpm not found in PATH"
        pnpm --version || echo "pnpm command failed"

    - name: Set NPM registry URL
      shell: bash
      run: npm config set registry https://registry.npmjs.org